name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
  - cron:  '0 0 * * *'

jobs:
  ci:
    name: CI with Default Configuration
    runs-on: ubuntu-latest

    steps:
    - name: Fetch Sources
      uses: actions/checkout@v2
    - name: Build Project
      run: cargo build --verbose --all-targets
    - name: Run Tests
      run: cargo test --verbose
